spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka