server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wifior/config-repo.git
logging:
  level:
    root: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
