server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否要在eureka上注册
    fetch-registry: false       #是否从EurekaServer获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false  #false 关闭自我保护
    eviction-interval-timer-in-ms: 4000    #清理间隔(ms)
